### ISSUE TITLE
rmt_wait_tx_done

### ISSUE THREAD

**Issue by ghost** [ExploreEmbedded/ESP32_RMT#2]
With the current new Arduino SDK for the ESP32 the declaration of rmt_wait_tx_done changed.

`esp_err_t rmt_wait_tx_done(rmt_channel_t channel, TickType_t wait_time);`

I changed everything in your lib to:
`rmt_wait_tx_done((rmt_channel_t)channel,( TickType_t ) 10);`

Is this the correct way? Id never coded something for the RTOS, thats why im asking.

**Comment by Vorms** [comment]
Hello, it's nice to start the work. 
Do you want to write in fine a ir remote library compatible with ir remote library already available for other micro controller? 
If yes I want to encourage you because we need it ! Esp32 is a very nice piece! Best regards

**Comment by ghost** [comment]
Sorry, but i did not understand what you wrote.
I guess you meant i should create a library to make it compatible with the other standard Arduino codes?
No i cant, because i do not have enough time for such things. But if you took a closer look you can almost directly use it. The Syntax for sending is the same as any other librarys. I didnt archived receiving yet. I found out that : ` rmt_wait_tx_done((rmt_channel_t)channel,( TickType_t ) 0);` is more usefull for me because the current thread wont be blocked.
